<?php 

    session_start();

    global $base_url ;
    $front_url = $_SERVER['SERVER_NAME'];

    require_once 'Medoo.php';
    use Medoo\Medoo;

    try{
        $database = new Medoo([
            'type' => 'mysql',
            'host' => 'mysql-promote-cms.alwaysdata.net',
            'database' => 'promote-cms_bdd',
            'username' => '347331',
            'password' => '3kzJ&@tCzKzd3JF7'
        ]);
    }

    catch(PDOException $e){
        echo "Erreur : ".$e->getMessage();
    }

    # Rewrite the datetime string based on timestamp generated by SQL
    function rewriteDatetime($datetime){


        # DEFAULT TIME STAMP STRING FORMAT : YYYY-MM-DD
        $day = $datetime[8].$datetime[9];
        $month = $datetime[5].$datetime[6];
        $year = $datetime[0].$datetime[1].$datetime[2].$datetime[3];
        $rewriteMonth = "";

        switch($month){
            case "01":
                $rewriteMonth = "Janvier";
                break;
            case "02":
                $rewriteMonth = "Février";
                break;
            case "03":
                $rewriteMonth = "Mars";
                break;
            case "04":
                $rewriteMonth = "Avril";
                break;
            case "05":
                $rewriteMonth = "Mai";
                break;
            case "06":
                $rewriteMonth = "Juin";
                break;
            case "07":
                $rewriteMonth = "Juillet";
                break;
            case "08":
                $rewriteMonth = "Aout";
                break;
            case "09":
                $rewriteMonth = "Septembre";
                break;
            case "10":
                $rewriteMonth = "Octobre";
                break;
            case "11":
                $rewriteMonth = "Novembre";
                break;
            case "12":
                $rewriteMonth = "Décembre";
                break;

        }

        $rewrite = $day." ".$rewriteMonth." ".$year;
        return $rewrite;
    }

?>